

DESKTOP_ENVIRONMENT = {
    "<————Official————>": None,
    "Budgie": "budgie",
    "Cinnamon": "cinnamon",
    "Cutefish": "cutefish",
    "Deepin": "deepin",
    "Enlightenment": "enlightenment",
    "GNOME": "gnome",
    "GNOME Flashback": "gnome-flashback",
    "KDE Plasma": "plasma",
    "LXDE": "lxde-gtk3",
    "LXQt": "lxqt",
    "MATE": "mate",
    "Sugar": "sugar",
    "UKUI": "ukui",
    "Xfce": "xfce4",
    "<————Unofficial————>": None,
    "CDE": "cdedesktopenv",
    "COSMIC": "cosmic-epoch-git",
    "EDE": "ede",
    "KDE1": "kde1-kdebase-git",
    "Liri": "liri-shell-git",
    "Lumina": "lumina-desktop",
    "Maui Shell": "maui-shell-git",
    "Moksha": "moksha-git",
    "Pantheon": "pantheon-session-git",
    "PaperDE": "paperde",
    "Phosh": "phosh",
    "theDesk": "thedesk"
}