LANGUAGE = {"Afrikaans": "af_ZA.UTF-8",
        "Albanian": "sq_AL.UTF-8", 
        "Amharic": "am_ET.UTF-8", 
         
        "Arabic (Algeria)": "ar_DZ.UTF-8", 
        "Arabic (Bahrain)": "ar_BH.UTF-8", 
        "Arabic (Egypt)": "ar_EG.UTF-8",
        "Arabic (Iraq)": "ar_IQ.UTF-8", 
        "Arabic (Jordan)": "ar_JO.UTF-8", 
        "Arabic (Kuwait)": "ar_KW.UTF-8",
        "Arabic (Lebanon)": "ar_LB.UTF-8", 
        "Arabic (Libya)": "ar_LY.UTF-8", 
        "Arabic (Mauritania)": "ar_MR.UTF-8",
        "Arabic (Morocco)": "ar_MA.UTF-8", 
        "Arabic (Oman)": "ar_OM.UTF-8", 
        "Arabic (Qatar)": "ar_QA.UTF-8",
        "Arabic (Saudi Arabia)": "ar_SA.UTF-8", 
        "Arabic (Syria)": "ar_SY.UTF-8", 
        "Arabic (Tunisia)": "ar_TN.UTF-8",
        "Arabic (UAE)": "ar_AE.UTF-8", 
        "Arabic (Yemen)": "ar_YE.UTF-8", 
        
        "Armenia": "hy_AM.UTF-8",
        "Assamese": "as_IN.UTF-8", 
        "Azerbaijani [Latin]": "az_Latn_AZ.UTF-8", 
        "Basque": "eu_ES.UTF-8",
        "Belarusian": "be_BY.UTF-8",
        "Bengali (Bangladesh)": "bn_BD.UTF-8",
        "Bengali (India)": "bn_IN.UTF-8",
        "Bosnian": "bs_Latn_BA.UTF-8", 
        "Bulgarian": "bg_BG.UTF-8",
        "Burmese": "my_MM.UTF-8",
        "Catalan": "ca_ES.UTF-8", 
        
        "Chinese [Hans]": "zh_Hans_CN.UTF-8", 
        "Chinese [Hans] (Singapore)": "zh_Hans_SG.UTF-8",
        "Chinese [Hant] (Hong Kong)": "zh_Hant_HK.UTF-8", 
        "Chinese [Hant] (Macao)": "zh_Hant_MO.UTF-8", 
        "Chinese [Hant] (Taiwan)": "zh_Hant_TW.UTF-8",
        
        "Croatian": "hr_HR.UTF-8", 
        "Czech": "cs_CZ.UTF-8", 
        "Danish": "da_DK.UTF-8",
        
        "Dutch (Belgium)": "nl_BE.UTF-8",
        "Dutch (Netherlands)": "nl_NL.UTF-8", 
        
        "English (Australia)": "en_AU.UTF-8", 
        "English (Beglium)": "en_BE.UTF-8",
        "English (Canada)": "en_CA.UTF-8", 
        "English (Cameroon)": "en_CM.UTF-8", 
        "English (Ghana)": "en_GH.UTF-8",
        "English (Hong Kong)": "en_HK.UTF-8", 
        "English (India)": "en_IN.UTF-8", 
        "English (Ireland)": "en_IE.UTF-8",
        "English (Kenya)": "en_KE.UTF-8", 
        "English (Mauritius)": "en_MU.UTF-8", 
        "English (New Zealand)": "en_NZ.UTF-8",
        "English (Nigeria)": "en_NG.UTF-8", 
        "English (Philipinnes)": "en_PH.UTF-8", 
        "English (Singapore)": "en_SG.UTF-8",
        "English (South Africa)": "en_ZA.UTF-8", 
        "English (Tanzania)": "en_TZ.UTF-8", 
        "English (United Kingdom)": "en_GB.UTF-8",
        "English (United Stated)": "en_US.UTF-8", 
        "English (Zambia)": "en_ZM.UTF-8", 
        
        "Estonian": "et_EE.UTF-8",
        "Filipino [Latin]": "fil_PH.UTF-8", 
        "Finnish": "fi_FI.UTF-8", 
        
        "French (Algeria)": "fr_DZ.UTF-8",
        "French (Beglium)": "fr_BE.UTF-8", 
        "French (Canada)": "fr_CA.UTF-8", 
        "French (Cameroon)": "fr_CM.UTF-8",
        "French (Democratic Rep. of the Congo)": "fr_CD.UTF-8", 
        "French (France)": "fr_FR.UTF-8", 
        "French (Ivory Cast)": "fr_CI.UTF-8",
        "French (Luxembourg)": "fr_LU.UTF-8", 
        "French (Mauritania)": "fr_MR.UTF-8", 
        "French (Mauritius)": "fr_MU.UTF-8",
        "French (Senegal)": "fr_SN.UTF-8", 
        "French (Switzerland)": "fr_CH.UTF-8", 
        "French (Tunisia)": "fr_TN.UTF-8",
        
        "Galicia": "gl_ES.UTF-8", 
        "Ganda": "lg_UG.UTF-8", 
        "Georgian": "ka_GE.UTF-8",
        
        "German (Austria)": "de_AT.UTF-8", 
        "German (Germany)": "de_DE.UTF-8", 
        "German (Luxembourg)": "de_LU.UTF-8",
        "German (Switzerland)": "de_CH.UTF-8", 
        
        "Greek": "el_GR.UTF-8", 
        "Gujarati (India)": "gu_IN.UTF-8",
        "Hausa": "ha_Latn_NG.UTF-8", 
        "Hebrew": "he_IL.UTF-8", 
        "Hindi (India)": "hi_IN.UTF-8",
        "Hungarian": "hu_HU.UTF-8", 
        "Icelandic": "is_IS.UTF-8", 
        "Igbo": "ig_NG.UTF-8",
        "Indonesian": "id_ID.UTF-8", 
        
        "Italian (Italy)": "it_IT.UTF-8", 
        "Italian (Switzerland)": "it_CH.UTF-8",
        
        "Japanese": "ja_JP.UTF-8", 
        "Kannada (India)": "kn_IN.UTF-8", 
        "Kazakh": "kk_Cyrl_KZ.UTF-8",
        "Khmer": "km_KH.UTF-8", 
        "Kinyarwanda": "rw_RW.UTF-8", 
        "Konkani (India)": "kok_IN.UTF-8",
        "Korean": "ko_KR.UTF-8", 
        "Lao": "lo_LA.UTF-8", 
        "Latvian": "lv_LV.UTF-8",
        "Lithauian": "lt_LT.UTF-8", 
        "Macedonian": "mk_MK.UTF-8", 
        "Malay": "ms_MY.UTF-8",
        "Malayalam (India)": "ml_IN.UTF-8", 
        "Maltese": "mt_MT.UTF-8", 
        "Marathi (Indian)": "mr_IN.UTF-8",
        "Mongolian [Cyrillic]": "mn_Cyrl_MN.UTF-8", 
        "Nepali": "ne_NP.UTF-8", 
        "Norwegian (Bokmål)": "nb_NO.UTF-8",
        "Norwegen (Nynorsk)": "nn_NO.UTF-8", 
        "Oriya (India)": "or_IN.UTF-8", 
        "Oromo": "om_IN.UTF-8",
        "Polish": "pl_PL.UTF-8", 
        
        "Portuguese (Angola)": "pt_AO.UTF-8", 
        "Portuguese (Brazil)": "pt_BR.UTF-8",
        "Portuguese (Macao)": "pt_MO.UTF-8", 
        "Portuguese (Mozambique)": "pt_MZ.UTF-8", 
        "Portuguese (Portugal)": "pt_PT.UTF-8",
        
        "Punjabi (India)": "pa_Guru_IN.UTF-8", 
        "Romanian": "ro_RO.UTF-8", 
        "Russian": "ru_RU.UTF-8",
        
        "Serbian [Latin] (Montengro)": "sr_Latn_ME.UTF-8", 
        "Serbian [Cyrillic] (Serbia)": "sr_Cyrl_RS.UTF-8", 
        "Serbian [Latin] (Serbia)": "sr_Latn_RS.UTF-8",
        
        "Sinhala": "si_LK.UTF-8", 
        "Slovak": "sk_SK.UTF-8", 
        "Slovenian": "sl_SI.UTF-8",
        
        "Spanish (Argentina)": "es_AR.UTF-8", 
        "Spanish (Bolivia)": "es_BO.UTF-8", 
        "Spanish (Chile)": "es_CL.UTF-8",
        "Spanish (Colombia)": "es_CO.UTF-8", 
        "Spanish (Costa Rica)": "es_CR.UTF-8", 
        "Spanish (Dominican Republic)": "es_DO.UTF-8",
        "Spanish (Ecuador)": "es_EC.UTF-8", 
        "Spanish (El Salvador)": "es_SV.UTF-8", 
        "Spanish (Guatemala)": "es_GT.UTF-8",
        "Spanish (Honduras)": "es_HN.UTF-8", 
        "Spanish (Mexico)": "es_MX.UTF-8", 
        "Spanish (Nicaragua)": "es_NI.UTF-8",
        "Spanish (Panama)": "es_PA.UTF-8", 
        "Spanish (Paraguay)": "es_PY.UTF-8", 
        "Spanish (Peru)": "es_PE.UTF-8",
        "Spanish (Puerto Rico)": "es_PR.UTF-8", 
        "Spanish (Spain)": "es_ES.UTF-8", 
        "Spanish (United States)": "es_US.UTF-8",
        "Spanish (Uruguay)": "es_UY.UTF-8", 
        "Spanish (Venezuela)": "es_VE.UTF-8", 
        
        "Swahili (Kenya)": "sw_KE.UTF-8", 
        "Swahili (Tanzania)": "sw_TZ.UTF-8", 
        
        "Swedish": "sv_SE.UTF-8",
        "Tamil (India)": "ta_IN.UTF-8", 
        "Telugu (India)": "te_IN.UTF-8", 
        "Thai": "th_TH.UTF-8",
        "Turkish": "tr_TR.UTF-8", 
        "Ukrainian": "uk_UA.UTF-8", 
        "Urdu (India)": "ur_IN.UTF-8",
        "Urdu (Pakistan)": "ur_PK.UTF-8",
        "Uzbek [Cyrillic]": "uz_Cyrl_UZ.UTF-8",
        "Uzbek [Latin]": "uz_Latn_UZ.UTF-8", 
        "Viatnamese": "vi_VN.UTF-8", 
        "Welsh (United Kingdom)": "cy_GB.UTF-8",
        "Yoruba [Latin]": "yo_NG.UTF-8", 
        "Zulu": "zu_ZA.UTF-8"
        }